Feature/cart list
kitab-bazar/client pull request #17
Opened 2022-01-25 09:29 UTC by barshathakuri

Add cart page

2022-01-26 09:51 UTC, AdityaKhatri commented on app/Base/components/Navbar/index.tsx
>                      {authenticated && user && (
Use ButtonLikeLink

2022-01-26 09:56 UTC, AdityaKhatri requested changes

2022-01-26 09:56 UTC, AdityaKhatri commented on app/views/CartPage/index.tsx
> +import { CartListQuery, CartListQueryVariables, DeleteCartItemsMutation, DeleteCartItemsMutationVariables } from '#generated/types';
```suggestion
import {
    CartListQuery,
    CartListQueryVariables,
    DeleteCartItemsMutation,
    DeleteCartItemsMutationVariables,
} from '#generated/types';
```

2022-01-26 09:56 UTC, AdityaKhatri commented on app/views/CartPage/index.tsx
> +}
These can be taken from generated which will reduce redundancy

2022-01-26 09:56 UTC, AdityaKhatri commented on app/views/CartPage/index.tsx
> +    const { id, price, authors, image, title, quantity, removeBookFromCartList, cartId } = props;
drop in multiple lines

2022-01-26 09:56 UTC, AdityaKhatri commented on app/views/CartPage/index.tsx
> +        authors?.map((d) => d.name).join(', ')
make a separate utility function to join strings

2022-01-26 09:56 UTC, AdityaKhatri commented on app/views/CartPage/index.tsx
> +    }, [cartId]);
set name of button to cartId and directly set removeBookFromCartList in onClick.

2022-01-26 09:56 UTC, AdityaKhatri commented on app/views/CartPage/index.tsx
> +                    </div>
Use message component

2022-01-26 09:56 UTC, AdityaKhatri commented on app/views/CartPage/index.tsx
> +        refetch();
refetch should be done after delete is completed.

2022-01-26 09:56 UTC, AdityaKhatri commented on app/views/CartPage/index.tsx
> +                                ))
define type of b and use ListView

2022-01-26 12:47 UTC, tnagorra requested changes

2022-01-26 12:47 UTC, tnagorra commented on app/Base/components/Navbar/index.tsx
> +                    </Link>
We should never nest button inside link.
The semantics is not correct.

2022-01-26 12:47 UTC, tnagorra commented on app/Base/configs/routes.tsx
> +    path: '/cart-page/',
Let's remove `-page` from page url

2022-01-26 12:47 UTC, tnagorra commented on app/Base/configs/routes.tsx
> +    title: 'My Cart Page',
Let's remove `Page` from title

2022-01-26 12:47 UTC, tnagorra commented on app/views/CartPage/index.tsx
> +import styles from './styles.css';
Move relative imports after absolute imports

2022-01-26 12:47 UTC, tnagorra commented on app/views/CartPage/index.tsx
> +                }
Please fetch id for image

2022-01-26 12:47 UTC, tnagorra commented on app/views/CartPage/index.tsx
> +                id
The indentation is not correct

2022-01-26 12:47 UTC, tnagorra commented on app/views/CartPage/index.tsx
> +interface Book {
```suggestion
interface CartContentProps {
```

2022-01-26 12:47 UTC, tnagorra commented on app/views/CartPage/index.tsx
> +    removeBookFromCartList: (id: string) => void;
```suggestion
    onBookRemoveFromCartList: (id: string) => void;
```

2022-01-26 12:47 UTC, tnagorra commented on app/views/CartPage/index.tsx
> +                        />
Use number output

2022-01-26 12:47 UTC, tnagorra commented on app/views/CartPage/index.tsx
> +                            />
Use number output

2022-01-26 12:47 UTC, tnagorra commented on app/views/CartPage/index.tsx
> +                            />
Why use NumberInput here without onChange

2022-01-26 12:47 UTC, tnagorra commented on app/views/CartPage/index.tsx
> +                        autoFocus
Why add autoFocus to two buttons?

2022-01-26 12:47 UTC, tnagorra commented on app/views/CartPage/index.tsx
> +                        onClick={undefined}
Let's handle this button or disable this button and add a fixme/todo

2022-01-26 12:47 UTC, tnagorra commented on app/views/CartPage/index.tsx
> +                                    <CartContent
Please use ListView.
ListView handles all of these cases like loading, empty, etc.

2022-01-26 12:47 UTC, tnagorra commented on app/views/CartPage/index.tsx
> +                                data.cartItems.results.map((b: any) => (
Let's not use `any` type

2022-01-26 12:47 UTC, tnagorra commented on app/views/CartPage/index.tsx
> +    const removeCartItem = (id: string) => {
Please use useCallback

2022-01-26 12:47 UTC, tnagorra commented on app/views/CartPage/index.tsx
> +            </Button>
Let's handle this or disable this button and add a FIXME/TODO comment

Also, why add "autoFocus" on button?

2022-01-26 12:47 UTC, tnagorra commented on app/views/CartPage/styles.css
> +                }
let's not use asymmetric spacing to fix styling issues

2022-01-27 04:31 UTC, barshathakuri commented on app/views/CartPage/index.tsx
> +                }
There is no id for image in API

2022-01-31 10:24 UTC, closed without merging