Add Individual Profile page
kitab-bazar/client pull request #21
Opened 2022-01-31 14:32 UTC by subinasr

2022-01-31 16:44 UTC, AdityaKhatri requested changes
@subinasr if multiple people are working on the profiles. Lets wrap and merge this one up as soon as possible.

2022-01-31 16:44 UTC, AdityaKhatri commented on app/Base/configs/routes.tsx
> +    visibility: 'is-anything', // TODO: change visibility to 'is-authenticated'
why add todo?

2022-01-31 16:44 UTC, AdityaKhatri commented on app/views/Profile/IndividualProfile/index.tsx
> +type StatusType = 'RECEIVED' | 'PACKED' | 'COMPLETED' | 'CANCELLED';
Get this from generated if possible

2022-01-31 16:44 UTC, AdityaKhatri commented on app/views/Profile/IndividualProfile/index.tsx
> +    const orderListRendererParams = useCallback((_, data: OrderListQuery) => ({
```suggestion
    const orderListRendererParams: OrderListRendererProps = useCallback((_, data: OrderListQuery) => ({
```

2022-01-31 17:00 UTC, subinasr commented on app/Base/configs/routes.tsx
> +    visibility: 'is-anything', // TODO: change visibility to 'is-authenticated'
For some reason, when I change the visibility to 'is-authenticated', the URL '/profile/' redirects to the home page. Need to understand this.

2022-02-01 08:47 UTC, AdityaKhatri requested changes

2022-02-01 08:47 UTC, AdityaKhatri commented on app/views/OrderList/index.tsx
> +function BookListRenderer(props: BookListProps) {
Rename to Book

2022-02-01 08:47 UTC, AdityaKhatri commented on app/views/Profile/index.tsx
> +
read directly

2022-02-02 05:19 UTC, AdityaKhatri requested changes

2022-02-02 05:19 UTC, AdityaKhatri commented on app/Base/components/Navbar/index.tsx
> +                                    to="/profile/"
use from routes, use SmartLink

2022-02-02 05:19 UTC, AdityaKhatri commented on app/Base/configs/routes.tsx
> +    visibility: 'is-authenticated', // TODO: change visibility to 'is-authenticated'
remove TODO

2022-02-02 05:19 UTC, AdityaKhatri commented on app/views/OrderList/index.tsx
> +    }), []);
send this here

2022-02-02 06:00 UTC, AdityaKhatri approved these changes

2022-02-02 06:01 UTC, merged