Add useTranslation hook
kitab-bazar/client pull request #22
Opened 2022-02-02 05:11 UTC by AdityaKhatri

2022-02-03 03:40 UTC, tnagorra commented on app/Base/configs/lang.ts
> +export const commonLang = {
Any reason we have these spaces after nepali words?

2022-02-03 03:44 UTC, tnagorra approved these changes

2022-02-03 04:40 UTC, frozenhelium commented on app/Base/context/LanguageContext.ts
> +        console.warn('Trying to set language', lang);
```suggestion
        console.error('Trying to set language before the language context was initialized', lang);
```

2022-02-03 04:44 UTC, frozenhelium commented on app/Base/hooks/useTranslation.ts
> +type Trans<T> = {
```suggestion
type Translations<T> = {
```

2022-02-03 04:48 UTC, frozenhelium requested changes
Lets only use `strings` for translated strings so that it's easier to statically analyze code base and find out the usage

Eg: `const strings = useTranslation(homePage);`

2022-02-03 06:17 UTC, AdityaKhatri commented
> Lets only use `strings` for translated strings so that it's easier to statically analyze code base and find out the usage
> 
> Eg: `const strings = useTranslation(homePage);`

@frozenhelium Makes sense, but we might have to use 2 objects in the same page and that creates an issue.

2022-02-03 06:23 UTC, subinasr approved these changes

2022-02-03 06:23 UTC, merged

2022-02-04 04:31 UTC, frozenhelium commented
@AdityaKhatri we can still do
```
const homeStrings = useTranslation(homePage);
const commonStrings = useTranslation(commonLang);
const strings = {
    ...homeStrings,
    ...commonStrings,
};
```