Add Edit Profile modal for individual user
kitab-bazar/client pull request #24
Opened 2022-02-02 12:29 UTC by subinasr

depends on https://github.com/toggle-corp/kitab-server/pull/22

2022-02-03 06:34 UTC, AdityaKhatri requested changes

2022-02-03 06:34 UTC, AdityaKhatri commented on app/views/Profile/IndividualProfile/EditProfileModal/index.tsx
> +            <div className={styles.description}>
unnecessary div

2022-02-03 06:34 UTC, AdityaKhatri commented on app/views/Profile/IndividualProfile/EditProfileModal/styles.css
> +}
unnecessary style page

2022-02-03 06:34 UTC, AdityaKhatri commented on app/views/Profile/IndividualProfile/index.tsx
> +        <Link
Use SmartLink

2022-02-03 06:34 UTC, AdityaKhatri commented on app/views/Profile/IndividualProfile/index.tsx
> +    }, [showEditProfileModal]);
use directly

2022-02-04 03:43 UTC, frozenhelium commented on app/views/Profile/IndividualProfile/index.tsx
> +    }, [showEditProfileModal]);
Even better
```jsx
<Button
  name={undefined}
  variant="general"
  onClick={showEditProfileModal}
  icons={<IoPencil />}
>
  Edit Profile
</Button>
```

2022-02-04 08:43 UTC, AdityaKhatri commented on app/views/Profile/IndividualProfile/index.tsx
> +    }, [showEditProfileModal]);
yes, my comment exactly :+1:

2022-02-04 09:28 UTC, merged