School package view for moderators
kitab-bazar/client pull request #83
Opened 2022-03-10 09:17 UTC by samshara

part of https://github.com/kitab-bazar/kitab-bazar/issues/66,
part of https://github.com/kitab-bazar/kitab-bazar/issues/67,
part of https://github.com/kitab-bazar/kitab-bazar/issues/73

2022-03-18 11:15 UTC, subinasr requested changes

2022-03-18 11:15 UTC, subinasr commented on app/views/Moderation/CourierPackages/Actions/UpdatePackageModal/index.tsx
> +                );
We can use ErrorMessage component here instead of this nested <div>

2022-03-18 11:15 UTC, subinasr commented on app/views/Moderation/PublisherPackages/Actions/UpdatePackageModal/index.tsx
> +                    { variant: 'error' },
Same here.

2022-03-18 11:15 UTC, subinasr commented on app/views/Moderation/SchoolPackages/Actions/UpdatePackageModal/index.tsx
> +                    { variant: 'error' },
Maybe use ErrorMessage component here too.

2022-03-21 05:03 UTC, barshathakuri approved these changes

2022-03-21 05:13 UTC, merged