Add support for Individual and Institution user types
kitab-bazar/client pull request #95
Opened 2022-03-22 06:29 UTC by subinasr

2022-03-22 08:22 UTC, barshathakuri requested changes

2022-03-22 08:22 UTC, barshathakuri commented on app/views/Register/RegisterForm/index.tsx
> +    console.warn('user types', userTypeOptions, includedUserTypes);
Please remove console

2022-03-22 08:22 UTC, barshathakuri commented on app/views/Register/RegisterForm/index.tsx
> +const includedUserTypes: UserTypeEnum[] = ['SCHOOL_ADMIN', 'PUBLISHER', 'INSTITUTIONAL_USER', 'INDIVIDUAL_USER'];
Please move in Multiple lines

2022-03-23 08:15 UTC, samshara commented
@subinasr @amarshahi  we won't be supporting individuals and institutions right now.

2022-03-23 08:15 UTC, closed without merging